#!/usr/bin/env ruby
require 'msgtrail/publish'
require 'msgtrail/version'
Dotenv.load
if ARGV[0]
  Msgtrail::Publish::to_file_system(Dir.getwd, ARGV[0])
else
  puts "Version: #{Msgtrail::VERSION}"
  puts "Usage: #{$PROGRAM_NAME} {theme-directory-name}"
end
